# Docker Compose para Dokploy
#
# INSTRUCCIONES DE DEPLOY EN DOKPLOY:
# 1. Crear nuevo proyecto "Compose" en Dokploy
# 2. Conectar el repositorio Git
# 3. Seleccionar este archivo: compose.dokploy.yml
# 4. Configurar las variables de entorno en el panel de Dokploy
# 5. Deploy!

services:
  # ====================================
  # PostgreSQL Database
  # ====================================
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - warynessy_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Puerto interno solo - no exponer en producción

  # ====================================
  # Aplicación Principal (Payload + Astro)
  # ====================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dokploy-network
      - default
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.warynessy-http.rule=Host(`warynessy.eneweb.es`)"
      - "traefik.http.routers.warynessy-http.entrypoints=web"
      - "traefik.http.routers.warynessy-http.middlewares=redirect-to-https"
      # HTTPS router
      - "traefik.http.routers.warynessy-https.rule=Host(`warynessy.eneweb.es`)"
      - "traefik.http.routers.warynessy-https.entrypoints=websecure"
      - "traefik.http.routers.warynessy-https.tls=true"
      - "traefik.http.routers.warynessy-https.tls.certresolver=letsencrypt"
      # Service
      - "traefik.http.services.warynessy-service.loadbalancer.server.port=3000"
      # Network
      - "traefik.docker.network=dokploy-network"
      # Redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    environment:
      NODE_ENV: production
      PORT: 3000
      # --- Database ---
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # --- Payload CMS ---
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_PUBLIC_SERVER_URL: ${PAYLOAD_PUBLIC_SERVER_URL}
      PUBLIC_PAYLOAD_API_URL: ${PUBLIC_PAYLOAD_API_URL}
      # --- Site ---
      PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
      PUBLIC_SITE_NAME: ${PUBLIC_SITE_NAME:-Restaurante Warynessy}
      # --- Bunny CDN ---
      BUNNY_CDN_URL: ${BUNNY_CDN_URL:-}
      BUNNY_STORAGE_ZONE_NAME: ${BUNNY_STORAGE_ZONE_NAME:-}
      BUNNY_API_KEY: ${BUNNY_API_KEY:-}
      BUNNY_STORAGE_PASSWORD: ${BUNNY_STORAGE_PASSWORD:-}
      # --- Google Services ---
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      GOOGLE_PLACE_ID: ${GOOGLE_PLACE_ID:-}
      PUBLIC_GOOGLE_ANALYTICS_ID: ${PUBLIC_GOOGLE_ANALYTICS_ID:-}
      PUBLIC_GOOGLE_MAPS_API_KEY: ${PUBLIC_GOOGLE_MAPS_API_KEY:-}
      # --- Instagram ---
      INSTAGRAM_ACCESS_TOKEN: ${INSTAGRAM_ACCESS_TOKEN:-}
      INSTAGRAM_USER_ID: ${INSTAGRAM_USER_ID:-}
      PUBLIC_INSTAGRAM_USERNAME: ${PUBLIC_INSTAGRAM_USERNAME:-}
      # --- Email (Resend) ---
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      EMAIL_FROM: ${EMAIL_FROM:-}
      EMAIL_TO: ${EMAIL_TO:-}
      # --- CoverManager ---
      PUBLIC_COVER_MANAGER_ID: ${PUBLIC_COVER_MANAGER_ID:-}
    # No exponer puertos - Traefik de Dokploy maneja el routing
    expose:
      - "3000"
    volumes:
      # Persistir media uploads (si no usas CDN exclusivamente)
      - warynessy_media:/app/media
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/admin"]
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 512M

volumes:
  warynessy_postgres_data:
    driver: local
  warynessy_media:
    driver: local

networks:
  dokploy-network:
    external: true
