# Docker Compose para Dokploy
#
# INSTRUCCIONES DE DEPLOY EN DOKPLOY:
# 1. Crear proyecto "Compose" en Dokploy
# 2. Conectar el repositorio Git
# 3. Seleccionar este archivo: compose.dokploy.yml
# 4. Configurar las variables de entorno en el panel de Dokploy
# 5. Deploy!
# 6. Configurar dominios:
#    - warynessy.eneweb.es → puerto interno 4321 del servicio "web" (CONFIGURAR EN DOKPLOY UI)
#    - admin.warynessy.eneweb.es → puerto interno 3000 del servicio "payload" (CONFIGURAR EN DOKPLOY UI)
#    - NO USAR docker-compose.yml (ese es para dev local), USAR ESTE: compose.dokploy.yml

services:
  # ====================================
  # PostgreSQL Database
  # ====================================
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-warynessy}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-warynessy_prod_secure}
      POSTGRES_DB: ${POSTGRES_DB:-warynessy}
    volumes:
      - warynessy_postgres_data:/var/lib/postgresql/data
    networks:
      - dokploy-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-warynessy} -d ${POSTGRES_DB:-warynessy}" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  # ====================================
  # Payload CMS (Admin + API)
  # ====================================
  payload:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dokploy-network
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      DATABASE_URL: postgresql://${POSTGRES_USER:-warynessy}:${POSTGRES_PASSWORD:-warynessy_prod_secure}@db:5432/${POSTGRES_DB:-warynessy}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_PUBLIC_SERVER_URL: https://admin.warynessy.eneweb.es
      PUBLIC_PAYLOAD_API_URL: https://admin.warynessy.eneweb.es/api
      PUBLIC_SITE_URL: https://warynessy.eneweb.es
      PUBLIC_SITE_NAME: ${PUBLIC_SITE_NAME:-Restaurante Warynessy}
      BUNNY_CDN_URL: ${BUNNY_CDN_URL:-}
      BUNNY_STORAGE_ZONE_NAME: ${BUNNY_STORAGE_ZONE_NAME:-}
      BUNNY_API_KEY: ${BUNNY_API_KEY:-}
      BUNNY_STORAGE_PASSWORD: ${BUNNY_STORAGE_PASSWORD:-}
    expose:
      - "3000"
    volumes:
      - warynessy_media:/app/media
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/admin" ]
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 384M

  # ====================================
  # Astro Frontend (SSR)
  # ====================================
  web:
    build:
      context: .
      dockerfile: Dockerfile.astro
    restart: always
    depends_on:
      - payload
    networks:
      - dokploy-network
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 4321
      DATABASE_URL: postgresql://${POSTGRES_USER:-warynessy}:${POSTGRES_PASSWORD:-warynessy_prod_secure}@db:5432/${POSTGRES_DB:-warynessy}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PUBLIC_PAYLOAD_API_URL: https://admin.warynessy.eneweb.es/api
      PUBLIC_SITE_URL: https://warynessy.eneweb.es
      PUBLIC_SITE_NAME: ${PUBLIC_SITE_NAME:-Restaurante Warynessy}
      PUBLIC_BUNNY_CDN_URL: ${BUNNY_CDN_URL:-}
      PUBLIC_GOOGLE_ANALYTICS_ID: ${PUBLIC_GOOGLE_ANALYTICS_ID:-}
      PUBLIC_GOOGLE_MAPS_API_KEY: ${PUBLIC_GOOGLE_MAPS_API_KEY:-}
      PUBLIC_INSTAGRAM_USERNAME: ${PUBLIC_INSTAGRAM_USERNAME:-}
      PUBLIC_COVER_MANAGER_ID: ${PUBLIC_COVER_MANAGER_ID:-}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      EMAIL_FROM: ${EMAIL_FROM:-}
      EMAIL_TO: ${EMAIL_TO:-}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      GOOGLE_PLACE_ID: ${GOOGLE_PLACE_ID:-}
      INSTAGRAM_ACCESS_TOKEN: ${INSTAGRAM_ACCESS_TOKEN:-}
      INSTAGRAM_USER_ID: ${INSTAGRAM_USER_ID:-}
    expose:
      - "4321"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321/" ]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 256M

volumes:
  warynessy_postgres_data:
    driver: local
  warynessy_media:
    driver: local

networks:
  dokploy-network:
    external: true
