services:
  # Local database service removed in favor of external database

  payload:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    # Depends on db removed as we use external DB
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      DATABASE_URL: "${DATABASE_URL:-postgresql://warynessy:Warynessy2026SecurePass@72.62.183.215:5436/warynessy}"
      PAYLOAD_SECRET: "${PAYLOAD_SECRET}"
      PAYLOAD_PUBLIC_SERVER_URL: https://admin.warynessy.eneweb.es
      PUBLIC_PAYLOAD_API_URL: https://admin.warynessy.eneweb.es/api
      PUBLIC_SITE_URL: https://warynessy.eneweb.es
      PUBLIC_SITE_NAME: "${PUBLIC_SITE_NAME:-Restaurante Warynessy}"
      BUNNY_CDN_URL: "${BUNNY_CDN_URL:-}"
      BUNNY_STORAGE_ZONE_NAME: "${BUNNY_STORAGE_ZONE_NAME:-}"
      BUNNY_API_KEY: "${BUNNY_API_KEY:-}"
      BUNNY_STORAGE_PASSWORD: "${BUNNY_STORAGE_PASSWORD:-}"
    networks:
      - dokploy-network
    expose:
      - "3000"
    volumes:
      - warynessy_media:/app/public/media

  web:
    build:
      context: .
      dockerfile: Dockerfile.astro
    restart: always
    # Depends on payload remains unchanged
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      DATABASE_URL: "${DATABASE_URL:-postgresql://warynessy:Warynessy2026SecurePass@72.62.183.215:5436/warynessy}"
      PAYLOAD_SECRET: "${PAYLOAD_SECRET}"
      PUBLIC_PAYLOAD_API_URL: https://admin.warynessy.eneweb.es/api
      PUBLIC_SITE_URL: https://warynessy.eneweb.es
      PUBLIC_SITE_NAME: "${PUBLIC_SITE_NAME:-Restaurante Warynessy}"
      PUBLIC_BUNNY_CDN_URL: "${BUNNY_CDN_URL:-}"
      PUBLIC_GOOGLE_ANALYTICS_ID: "${PUBLIC_GOOGLE_ANALYTICS_ID:-}"
      PUBLIC_GOOGLE_MAPS_API_KEY: "${PUBLIC_GOOGLE_MAPS_API_KEY:-}"
      PUBLIC_INSTAGRAM_USERNAME: "${PUBLIC_INSTAGRAM_USERNAME:-}"
      PUBLIC_COVER_MANAGER_ID: "${PUBLIC_COVER_MANAGER_ID:-}"
      RESEND_API_KEY: "${RESEND_API_KEY:-}"
      EMAIL_FROM: "${EMAIL_FROM:-}"
      EMAIL_TO: "${EMAIL_TO:-}"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY:-}"
      GOOGLE_PLACE_ID: "${GOOGLE_PLACE_ID:-}"
      INSTAGRAM_ACCESS_TOKEN: "${INSTAGRAM_ACCESS_TOKEN:-}"
      INSTAGRAM_USER_ID: "${INSTAGRAM_USER_ID:-}"
    networks:
      - dokploy-network
    expose:
      - "3000"

volumes:
  # Local database volume removed as we use external DB
  warynessy_media:


networks:
  dokploy-network:
    external: true
